export enum ConfigEnum {
  DATABASE_URL = 'DATABASE_URL',

  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRATION_TIME = 'JWT_EXPIRATION_TIME',

  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_PASSWORD = 'REDIS_PASSWORD',
  REDIS_RECONNECT = 'REDIS_RECONNECT',
}

// declare enum LogEnum {
//   LOG_LEVEL = 'LOG_LEVEL',
//   LOG_ON = 'LOG_ON',
//   TIMESTAMP = 'TIMESTAMP',
// }
